import type { DMMF } from "@prisma/generator-helper";
import type { PrismaExtractorConfig } from "./config";

function mapPrismaTypeToTsType(
  prismaType: string,
  config: PrismaExtractorConfig
): string {
  return config.mapTypes[prismaType] || prismaType;
}

export function generateTsInterfaces(
  models: DMMF.Model[],
  enums: DMMF.DatamodelEnum[],
  config: PrismaExtractorConfig
): string {
  let content = `// This file is auto-generated by [sc-prisma-extractor](https://github.com/saulotarsobc/sc-prisma-extractor).
// Do not edit this file directly.

`;

  // Generate Enums
  enums.forEach((enumDef: DMMF.DatamodelEnum) => {
    if (config.enumOutputType === "type") {
      const values = enumDef.values
        .map((value: DMMF.EnumValue) => `"${value.name}"`) // Corrected: escaped double quotes within template literal
        .join(" | ");
      content += `export type ${enumDef.name} = ${values};

`;
    } else {
      content += `export enum ${enumDef.name} {
`;
      enumDef.values.forEach((value: DMMF.EnumValue) => {
        content += `  ${value.name} = "${value.name}",
`;
      });
      content += `}

`;
    }
  });

  // Generate Interfaces or Types
  models.forEach((model: DMMF.Model) => {
    const keyword = config.outputType === "type" ? "type" : "interface";
    const separator = config.outputType === "type" ? " =" : "";
    content += `export ${keyword} ${model.name}${separator} {
`;
    model.fields.forEach((field: DMMF.Field) => {
      const tsType = mapPrismaTypeToTsType(field.type, config);
      const isRelation = field.kind === "object"; // relation fields
      // Prisma DMMF exposes hasDefaultValue for scalar defaults (including autoincrement, now(), @updatedAt, enums with default)
      const hasDefault: boolean =
        typeof (field as any).hasDefaultValue === "boolean"
          ? (field as any).hasDefaultValue
          : false;
      const isUpdatedAt: boolean =
        typeof (field as any).isUpdatedAt === "boolean"
          ? (field as any).isUpdatedAt
          : false;
      const isOptional =
        !field.isRequired ||
        (config.relationFieldsOptional && isRelation) ||
        (config.defaultFieldsOptional &&
          !isRelation &&
          (hasDefault || isUpdatedAt));
      const isList = field.isList;
      content += `  ${field.name}${isOptional ? "?" : ""}: ${tsType}`; // Corrected: escaped double quotes within template literal
      if (isList) {
        content += "[]";
      }
      content += ";\n";
    });
    content += `}

`;
  });

  return content;
}
