#!/usr/bin/env node
import * as path from 'path';
import * as fs from 'fs';
import { extractSchema } from './utils/index';

async function main() {
  const args = process.argv.slice(2);

  if (args.length < 2) {
    console.error('Usage: sc-prisma-extractor <path-to-schema.prisma> <path-to-output.ts>');
    process.exit(1);
  }

  const schemaPath = args[0];
  const outputPath = args[1];

  try {
    const { models, enums } = await extractSchema(schemaPath);

    const fileContent = `// This file is auto-generated by sc-prisma-extractor.
// Do not edit this file directly.

export const models = ${JSON.stringify(models, null, 2)};

export const enums = ${JSON.stringify(enums, null, 2)};
`;

    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    fs.writeFileSync(outputPath, fileContent, 'utf-8');

    console.log(`✅ Schema extracted successfully to ${outputPath}`);

  } catch (error) {
    console.error('An error occurred:', error);
    process.exit(1);
  }
}

main();